### ISSUE TITLE
Deprecate the wiki "manual"

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser-visited#17]
There's a page called "manual" on the wiki that's always outdated. Better see if it contains anything useful for the book, and if not, delete the thing.

Also delete the wiki code samples contained in the javaparser test code, and the links to the wiki (javaparser.org and README.md?)

**Comment by SmiddyPence** [comment]
@matozoid do you have a link I can't see it... did you already delete it?

**Comment by matozoid** [comment]
Yeah, I deleted a lot a few weeks ago.
