### ISSUE TITLE
Examples are hard (for me) to copy because of the line numbers

### ISSUE THREAD

**Issue by fuhrmanator** [javaparser/javaparser-visited#21]
Thanks for writing this book!

The examples are cool, but the format of them in the eBook is annoying because one cannot easily copy them to an IDE. That is, the line numbers are included. Maybe I'm missing something obvious?

**Comment by SmiddyPence** [comment]
So I would say there are two options you can use the code in this repository for example these are the samples from Chapter 2. They're not like for like, but you should find partial and full solutions there:

https://github.com/javaparser/javaparser-visited/tree/master/src/main/java/org/javaparser/examples/chapter2

The other option is to remove them in the IDE, paste the code sample then use: 

Edit > Column Selection Mode  (CMD + Shift +  8 on Mac) then you can select the first character on every line at once and hit delete.

Hope that helps!
