### ISSUE TITLE
JavaSymbolSolver

### ISSUE THREAD

**Issue by MysterAitch** [javaparser/javaparser-visited#22]
I'm having another read through the book and have spotted that the symbol solver is referred to as "JavaSymbolSolver".

My understanding is that it is now the "JavaParser Symbol Solver".

If this understanding is correct, then please consider this minor edit :)

**Comment by SmiddyPence** [comment]
Yes bit tricky to unpick as the colloquial name now, is not the same as the class name. Think I will opt to use the colloquial name in the introduction and then have to switch the class name for explanation. 

Helped me identify a number of other segments that are still written as though the two libraries are separate.

**Comment by SmiddyPence** [comment]
Tidied, up and added a note to reader to be aware of the colloquial and class names. Updates will be in next version.
