### ISSUE TITLE
[EDITORIAL] Example uses File; text describes FileInputStream

### ISSUE THREAD

**Issue by ericprud** [javaparser/javaparser-visited#29]
1. p 11 has a

``` java
CompilationUnit cu = StaticJavaParser.parse(new File(FILE_PATH));
```

... p 12 describes that invokcation as the StaticJavaParser taking a FileInputStream (which you don't have to close).
... I think the example changed from a FileInputStream to a File without the description changing.

**Comment by SmiddyPence** [comment]
Thanks for the report. 

Latest changes to book will reflect this.
