### ISSUE TITLE
IllegalStateException when running the ResolveTypeInContext example from the book

### ISSUE THREAD

**Issue by abego** [javaparser/javaparser-visited#34]
When trying to run the ResolveTypeInContext example from the book I get an Exception:
```
java.lang.IllegalStateException: The parent of this TypeSolver cannot be itself.
    at com.github.javaparser.symbolsolver.resolution.typesolvers.ClassLoaderTypeSolver.setParent(ClassLoaderTypeSolver.java:60)
```
It occurs for this statement:
```
reflectionTypeSolver.setParent(reflectionTypeSolver);
```
(line 23 in https://github.com/javaparser/javaparser-visited/blob/master/src/main/java/org/javaparser/examples/chapter5/ResolveTypeInContext.java)

Removing the statement make the exception go away.

**Comment by abego** [comment]
May be a duplicate of https://github.com/javaparser/javaparser-visited/issues/28

**Comment by SmiddyPence** [comment]
Thanks for the report. 

Code samples and book should now reflect this.
