### ISSUE TITLE
Example text in book is out-dated, e.g. for `ResolveTypeInContext`

### ISSUE THREAD

**Issue by abego** [javaparser/javaparser-visited#35]
I just bought the book and I am trying out the examples. 

However I could not compile `ResolveTypeInContext` because `StaticJavaParser.getStaticConfiguration()` is not implemented. Using `StaticJavaParser.getConfiguration()` instead solved the issue.

I just checked with the example code in this repo (https://github.com/javaparser/javaparser-visited/blob/master/src/main/java/org/javaparser/examples/chapter5/ResolveTypeInContext.java) and noticed the bug is already fixed in that source code. However as I copied the example code from the book's PDF I ran into the problem.

According to the book it was last updated 2021-02-05, but the source code was 2019-04-15, i.e. nearly two years before the book was last published.

Please keep the Leanpub books you sell up-to-date with the source code in the repo.

**Comment by SmiddyPence** [comment]
Thanks for the report. 

Book is now updated.
