### ISSUE TITLE
Using deprecated method in sample code (JarTypeSolver.getJarTypeSolver)

### ISSUE THREAD

**Issue by abego** [javaparser/javaparser-visited#36]
In the chapter "Using the CombinedTypeSolver" of the book the sample code contains lines like this:
```
JarTypeSolver.getJarTypeSolver("jars/library1.jar"),
```

However, `JarTypeSolver.getJarTypeSolver` is deprecated, so the sample code should probably look like this:
```
new JarTypeSolver("jars/library1.jar"),
```

**Comment by SmiddyPence** [comment]
Thanks for the report. 

Code samples and book should now reflect this.
