### ISSUE TITLE
Some typos in the "JavaParser: Visited" book

### ISSUE THREAD

**Issue by chonton** [javaparser/javaparser-visited#5]
JavaParser: Visited 
published on 2018-04-07 

pg 11, childredNodes -> childrenNodes
pg 21, FielidDeclariton’s -> FieldDeclaration’s
pg 27 it’s -> its
pg 30 each threads personal -> each thread’s personal 

Probably an error:
pg 51 reflectionTypeSolver.setParent(reflectionTypeSolver);  -> reflectionTypeSolver.setParent(javaParserTypeSolver);

**Comment by SmiddyPence** [comment]
Hi Chas

Thank you for submitting these, it is really helpful.

We'll get 're corrections in the next version.

**Comment by SmiddyPence** [comment]
Thank you for your feedback! 

A new version is now available with these changes.
