### ISSUE TITLE
Error in code example (page 18)

### ISSUE THREAD

**Issue by quarks** [javaparser/javaparser-visited#8]
On page 18 you have the code line 
```ModifierVisitorAdapter<?> numericLiteralVisitor = new IntegerLiteralModifier();```
it should be
```ModifierVisitor<?> numericLiteralVisitor = new IntegerLiteralModifier();```
as the ModifierVisitorAdapter class does not exist.

**Comment by SmiddyPence** [comment]
Thank you for your feedback! 

A new version is now available with these changes.
