### ISSUE TITLE
Error in code (page 43)

### ISSUE THREAD

**Issue by quarks** [javaparser/javaparser-visited#9]
You have the code
```
class MyClass extends MySuperClass { 
    public void returnSomeValue() {
        return aField.size();
    }
}
```
This cannot be a void method because it returns a value. If you add the return type this will resolve the data type for aField but your example is to show that the solver may have to see other files, in this case the parent class. 
I suggest
```
class MyClass extends MySuperClass { 
    public void printSomeValue() {
        System.out.println(aField.size();
    }
}
```

**Comment by SmiddyPence** [comment]
Thank you for your feedback! 

A new version is now available with these changes.
